version: '3.1'
services:
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./public:/public
volumes:
  db-data: